# TypeProf 0.21.8

# Classes
class Planner
  attr_reader query_planner: BasicQueryPlanner
  attr_reader update_planner: BasicUpdatePlanner
  def initialize: (BasicQueryPlanner query_planner, BasicUpdatePlanner update_planner) -> void
  def create_query_plan: (String query, Transaction transaction) -> _Plan[_Scan]
  def execute_update: (String command, Transaction transaction) -> Integer

  private
  def verify_query: (QueryData query_data) -> nil
  def verify_update: (untyped data) -> nil
end
