# TypeProf 0.21.8

# Classes
class LockTable
  MAX_LOCKS: Integer

  @locks: Hash[untyped, Integer]
  @mutex: untyped
  @full: untyped

  def initialize: -> void
  def s_lock: (BlockId block_id) -> void
  def x_lock: (BlockId block_id) -> void
  def unlock: (BlockId block_id) -> Integer

  private
  def x_lock?: (BlockId block_id) -> bool
  def other_s_lock?: (BlockId block_id) -> bool
  def get_lock_value: (BlockId block_id) -> Integer
  def waiting_too_long: (Integer start_time) -> bool
end
