# TypeProf 0.21.8

# Classes
class BufferList
  @buffers: Hash[BlockId, Buffer]
  @pins: Array[BlockId]
  @buffer_manager: BufferManager

  def initialize: (BufferManager buffer_manager) -> void
  def get_buffer: (BlockId block_id) -> Buffer?
  def pin: (BlockId block_id) -> void
  def unpin: (BlockId block_id) -> void
  def unpin_all: -> void
end
