# TypeProf 0.21.8

# Classes
class Transaction
  @file_manager: untyped
  @buffer_manager: untyped
  @transaction_number: Integer
  @recovery_manager: untyped
  @concurrency_manager: untyped
  @buffers: untyped
  @@next_tx_num: Integer

  def self.next_tx_number: -> Integer
  def initialize: (untyped file_manager, untyped log_manager, untyped buffer_manager) -> void
  def commit: -> untyped
  def rollback: -> untyped
  def recover: -> untyped
  def pin: (untyped block_id) -> untyped
  def unpin: (untyped block_id) -> untyped
  def get_int: (untyped block_id, untyped offset) -> untyped
  def get_string: (untyped block_id, untyped offset) -> untyped
  def set_int: (untyped block_id, untyped offset, untyped value, untyped ok_to_log) -> untyped
  def set_string: (untyped block_id, untyped offset, untyped value, untyped ok_to_log) -> untyped
  def size: (untyped file_name) -> untyped
  def append: (untyped file_name) -> untyped
  def block_size: -> untyped
  def available_buffs: -> untyped
end
