# TypeProf 0.21.8

# Classes
class Transaction
  END_OF_FILE: Integer

  @file_manager: FileManager
  @buffer_manager: BufferManager
  @transaction_number: Integer
  @recovery_manager: RecoveryManager
  @concurrency_manager: ConcurrencyManager
  @buffers: BufferList
  @@next_tx_num: Integer

  def self.next_tx_number: -> Integer
  def initialize: (FileManager file_manager, LogManager log_manager, BufferManager buffer_manager) -> void
  def commit: -> void
  def rollback: -> void
  def recover: -> void
  def pin: (BlockId block_id) -> void
  def unpin: (BlockId block_id) -> void
  def get_int: (BlockId block_id, Integer offset) -> Integer
  def get_string: (BlockId block_id, Integer offset) -> String
  def set_int: (BlockId block_id, Integer offset, Integer value, bool ok_to_log) -> void
  def set_string: (BlockId block_id, Integer offset, String value, bool ok_to_log) -> void
  def size: (String file_name) -> untyped
  def append: (String file_name) -> untyped
  def block_size: -> Integer
  def available_buffs: -> Integer
end
