# TypeProf 0.21.8

# Classes
class CreateIndexData < ::Data
  def self.new: (String index_name, String table_name, String field_name) -> instance
    | (index_name: String, table_name: String, field_name: String) -> instance

  def self.[]: (String index_name, String table_name, String field_name) -> instance
    | (index_name: String, table_name: String, field_name: String) -> instance

  def self.members: () -> [ :index_name, :table_name, :field_name ]

  def members: () -> [ :index_name, :table_name, :field_name ]

  attr_reader index_name: String

  attr_reader table_name: String

  attr_reader field_name: String
end