# TypeProf 0.21.8

# Classes
class CreateIndexData < ::Data
  def self.new: (untyped index_name, untyped table_name, untyped field_name) -> instance
    | (index_name: untyped, table_name: untyped, field_name: untyped) -> instance

  def self.[]: (untyped index_name, untyped table_name, untyped field_name) -> instance
    | (index_name: untyped, table_name: untyped, field_name: untyped) -> instance

  def self.members: () -> [ :index_name, :table_name, :field_name ]

  def members: () -> [ :index_name, :table_name, :field_name ]

  attr_reader index_name: untyped

  attr_reader table_name: untyped

  attr_reader field_name: untyped
end