# TypeProf 0.21.8

# Classes
class CreateTableData < ::Data
  def self.new: (String table_name, Schema schema) -> instance
    | (table_name: Schema, schema: String) -> instance

  def self.[]: (String table_name, Schema schema) -> instance
    | (table_name: String, schema: Schema) -> instance

  def self.members: () -> [ :table_name, :schema ]

  def members: () -> [ :table_name, :schema ]

  attr_reader table_name: String

  attr_reader schema: Schema
end
