# TypeProf 0.21.8

# Classes
class CreateViewData < ::Data
  def self.new: (String view_name, QueryData query_data) -> instance
    | (view_name: String, query_data: QueryData) -> instance

  def self.[]: (String view_name, QueryData query_data) -> instance
    | (view_name: String, query_data: QueryData) -> instance

  def self.members: () -> [ :view_name, :query_data ]

  def members: () -> [ :view_name, :query_data ]

  attr_reader view_name: String

  attr_reader query_data: QueryData
end