# TypeProf 0.21.8

# Classes
class DeleteData < ::Data
  def self.new: (String table_name, Predicate predicate) -> instance
    | (table_name: String, predicate: Predicate) -> instance

  def self.[]: (String table_name, Predicate predicate) -> instance
    | (table_name: String, predicate: Predicate) -> instance

  def self.members: () -> [ :table_name, :predicate ]

  def members: () -> [ :table_name, :predicate ]

  attr_reader table_name: String

  attr_reader predicate: Predicate
end