# TypeProf 0.21.8

# Classes
class InsertData < ::Data
  def self.new: (untyped table_name, untyped field_names, untyped values) -> instance
    | (table_name: untyped, field_names: untyped, field_values: untyped) -> instance

  def self.[]: (untyped table_name, untyped field_names, untyped values) -> instance
    | (table_name: untyped, field_names: untyped, values: untyped) -> instance

  def self.members: () -> [ :table_name, :field_names, :values ]

  def members: () -> [ :table_name, :field_names, :values ]

  attr_reader table_name: untyped

  attr_reader field_names: untyped

  attr_reader values: untyped
end