# TypeProf 0.21.8

# Classes
class InsertData < ::Data
  def self.new: (String table_name, Array[String] field_names, Array[untyped] values) -> instance
    | (table_name: String, field_names: Array[String], values: Array[untyped]) -> instance

  def self.[]: (String table_name, Array[String] field_names, Array[untyped] values) -> instance
    | (table_name: String, field_names: Array[String], values: Array[untyped]) -> instance

  def self.members: () -> [ :table_name, :field_names, :values ]

  def members: () -> [ :table_name, :field_names, :values ]

  attr_reader table_name: String

  attr_reader field_names: Array[String]

  attr_reader values: Array[untyped]
end