# TypeProf 0.21.8

# Classes
class ModifyData < ::Data
  def self.new: (String table_name, String field_name, untyped new_value, Predicate predicate) -> instance
    | (table_name: String, field_name: String, new_value: untyped, predicate: Predicate) -> instance

  def self.[]: (String table_name, String field_name, untyped new_value, Predicate predicate) -> instance
    | (table_name: String, field_name: String, new_value: untyped, predicate: Predicate) -> instance

  def self.members: () -> [ :table_name, :field_name, :new_value, :predicate ]

  def members: () -> [ :table_name, :field_name, :new_value, :predicate ]

  attr_reader table_name: String

  attr_reader field_name: String

  attr_reader new_value: untyped

  attr_reader predicate: Predicate
end
