# TypeProf 0.21.8

# Classes
class Parser
  @lexer: SqlLexer

  def initialize: (String statement) -> void
  def field: -> String
  def constant: -> Constant
  def expression: -> Expression
  def term: -> Term
  def predicate: -> Predicate
  def query: -> QueryData
  
  def select_list: -> Array[String]
  def table_list: -> Array[String]
  def update_cmd: -> untyped
  def insert: -> InsertData
  def delete: -> DeleteData
  def modify: -> ModifyData
  def create: -> (CreateTableData | CreateViewData | CreateIndexData)
  def create_table: -> CreateTableData
  def create_view: -> CreateViewData
  def create_index: -> CreateIndexData
  def field_list: -> Array[String]
  def const_list: -> Array[Constant]
  def field_defs: -> Schema
  def field_def: -> Schema
  def field_type: (String field_name) -> Schema
end
