# TypeProf 0.21.8

# Classes
class Parser
  @lexer: SqlLexer

  def initialize: (String statement) -> void
  def field: -> untyped
  def constant: -> untyped
  def expression: -> untyped
  def term: -> untyped
  def predicate: -> untyped
  def query: -> untyped

  private
  def select_list: -> Array[untyped]
  def table_list: -> Array[untyped]
  def update_cmd: -> untyped
  def insert: -> untyped
  def delete: -> untyped
  def modify: -> untyped
  def create: -> untyped
  def create_table: -> untyped
  def create_view: -> untyped
  def create_index: -> untyped
  def field_list: -> Array[untyped]
  def const_list: -> Array[untyped]
  def field_defs: -> untyped
  def field_def: -> untyped
  def field_type: (untyped field_name) -> untyped
end
