# TypeProf 0.21.8

# Classes
class QueryData < ::Data
  def self.new: (Array[String] field_names, Array[String] table_names, Predicate predicate) -> instance
    | (field_names: Array[String], table_names: Array[String], predicate: Predicate) -> instance

  def self.[]: (Array[String] field_names, Array[String] table_names, Predicate predicate) -> instance
    | (field_names: Array[String], table_names: Array[String], predicate: Predicate) -> instance

  def self.members: () -> [ :field_names, :table_names, :predicate ]

  def members: () -> [ :field_names, :table_names, :predicate ]

  attr_reader field_names: Array[String]

  attr_reader table_names: Array[String]

  attr_reader predicate: Predicate
end