# TypeProf 0.21.8

# Classes
class ViewManager
  MAX_VIEW_DEF: Integer
  attr_accessor table_manager: TableManager
  def initialize: (bool is_new, TableManager table_manager, Transaction transaction) -> void
  def create_view: (String view_name, String view_def, Transaction transaction) -> void
  def get_view_definition: (String view_name, Transaction transaction) -> (String | nil)
end
