# TypeProf 0.21.8

# Classes
class BufferManager
  MAX_TIME: Integer
  
  @buffer_pool: Array[Buffer]
  @num_available: Integer
  @mutex: untyped
  @full: untyped

  def initialize: (FileManager file_manager, LogManager log_manager, Integer number_buffers) -> void
  def available: -> Integer
  def flush_all: (Integer transaction_number) -> Array[untyped]
  def unpin: (Buffer buffer) -> nil
  def pin: (BlockId block_id) -> Buffer

  private
  def waiting_too_long: (Integer start_time) -> bool
  def try_to_pin: (BlockId block_id) -> Buffer?
  def find_existing_buffer: (BlockId block_id) -> Buffer?
  def choose_unpinned_buffer: -> Buffer?
end
