# TypeProf 0.21.8

# Classes
class Buffer
  @file_manager: FileManager
  @log_manager: LogManager

  attr_accessor contents: Page
  attr_accessor block_id: BlockId?
  attr_accessor pins: Integer
  attr_accessor transaction_number: Integer
  attr_accessor lsn: Integer
  def initialize: (FileManager file_manager, LogManager log_manager) -> void
  def set_modified: (Integer transaction_number, Integer lsn) -> untyped
  def pinned?: -> bool
  def modifying_tx: -> Integer
  def assign_to_block: (BlockId b) -> Integer
  def flush: -> Integer?
  def pin: -> Integer
  def unpin: -> Integer
end
