# TypeProf 0.21.8

# Classes
class ProjectScan
  include _Scan

  attr_accessor scan: _Scan
  attr_accessor field_list: Array[String]
  def initialize: (_Scan scan, Array[String] field_list) -> void
end
