interface _Scan
  def before_first: () -> void
  def next: () -> bool
  def get_int: () -> int
  def get_string: () -> String
  def get_value: () -> Constant
  def has_field?: (String field_name) -> bool
  def close: () -> void
end
