# TypeProf 0.21.8

# Classes
class SelectScan
  include _Scan

  attr_accessor scan: untyped
  attr_accessor predicate: Predicate
  def initialize: (_Scan scan, Predicate predicate) -> void
  def set_int: (String field_name, Integer value) -> void
  def set_string: (String field_name, String value) -> void
  def set_value: (String field_name, Constant value) -> void
  def delete: -> void
  def insert: -> void
  def get_record_id: -> RecordId
  def move_to_record_id: (RecordId record_id) -> void
end
