# TypeProf 0.21.8

# Classes
class CheckpointRecord
  attr_reader transaction_number: Integer
  attr_reader operation_code: Integer
  def initialize: (untyped page) -> void
  def to_s: -> String
  def self.write_to_log: (untyped log_manager) -> untyped
end
