# TypeProf 0.21.8

# Classes
class CommitRecord
  attr_reader transaction_number: untyped
  attr_reader operation_code: untyped
  def initialize: (untyped page) -> void
  def to_s: -> String
  def self.write_to_log: (untyped log_manager, untyped transaction_number) -> untyped
end
