# TypeProf 0.21.8

# Classes
class SetIntRecord
  @block_id: untyped
  @offset: untyped
  @value: untyped

  attr_reader transaction_number: Integer
  attr_reader operation_code: Integer
  def initialize: (untyped page) -> void
  def to_s: -> String
  def undo: (Transaction transaction) -> untyped
  def self.write_to_log: (LogManager log_manager, Integer transaction_number, BlockId block_id, Integer offset, Integer value) -> untyped
end
