# TypeProf 0.21.8

# Classes
class SimpleDB
  LOG_FILE: String
  attr_reader block_size: Integer
  attr_reader buffer_size: Integer
  attr_reader log_file: String
  attr_reader file_manager: FileManager
  attr_reader buffer_manager: BufferManager
  attr_reader log_manager: LogManager
  attr_reader planner: Planner
  def initialize: (untyped db_directory_path, untyped block_size, untyped buffer_size) -> void
  def new_transaction: -> Transaction
end
