# TypeProf 0.21.8

# Classes
class ProductPlan
  include _Plan[ProductScan]
  attr_reader plan1: _Plan[_Scan]
  attr_reader plan2: _Plan[_Scan]
  attr_reader schema: Schema
  def initialize: (_Plan[_Scan] plan1, _Plan[_Scan] plan2) -> void
end
