# TypeProf 0.21.8

# Classes
class ProductPlan
  attr_reader plan1: untyped
  attr_reader plan2: untyped
  attr_reader schema: untyped
  def initialize: (untyped plan1, untyped plan2) -> void
  def open: -> untyped
  def blocks_accessed: -> untyped
  def records_output: -> untyped
  def distinct_values: (untyped field_name) -> untyped
end
