# TypeProf 0.21.8

# Classes
class ProductPlan
  attr_reader plan1: _Plan
  attr_reader plan2: _Plan
  attr_reader schema: Schema
  def initialize: (_Plan plan1, _Plan plan2) -> void
  def open: -> ProductScan
  def blocks_accessed: -> Integer
  def records_output: -> Integer
  def distinct_values: (String field_name) -> Integer
end
