# TypeProf 0.21.8

# Classes
class ProjectPlan
  include _Plan[ProjectScan]

  attr_reader plan: _Plan[_Scan]
  attr_reader schema: Schema
  def initialize: (_Plan[_Scan] plan, Array[String] field_name_list) -> void
end
