# TypeProf 0.21.8

# Classes
class SelectPlan
  include _Plan[SelectScan]

  attr_reader plan: _Plan[_Scan]
  attr_reader predicate: Predicate
  def initialize: (_Plan[_Scan] plan, Predicate predicate) -> void
end
