# TypeProf 0.21.8

# Classes
class SelectPlan
  attr_reader plan: untyped
  attr_reader predicate: untyped
  def initialize: (untyped plan, untyped predicate) -> void
  def open: -> untyped
  def blocks_accessed: -> untyped
  def records_output: -> untyped
  def distinct_values: (untyped field_name) -> Integer?
  def schema: -> untyped
end
