# TypeProf 0.21.8

# Classes
class TablePlan
  include _Plan[TableScan]

  attr_reader table_name: String
  attr_reader transaction: Transaction
  attr_reader layout: Layout
  attr_reader stat_info: StatInfo
  def initialize: (Transaction transaction, String table_name, MetadataManager metadata_manager) -> void
end
